### ISSUE TITLE
貌似flutter依赖下载不了

### ISSUE THREAD

**Issue by nanchaodong** [zhujian1989/MyArchitecture#1]
初学者  不知道如下的错误怎么解决

 Because every version of flutter_test from sdk depends on http 0.12.0 and flutter_cache_manager ^0.1.0-rc.1 depends on http ^0.11.3+14, flutter_test from sdk is incompatible with flutter_cache_manager ^0.1.0-rc.1.

Because cached_network_image >=0.4.1 <0.4.2 depends on flutter_cache_manager ^0.1.1 and cached_network_image ^0.4.2 depends on flutter_cache_manager ^0.1.2, cached_network_image ^0.4.1 requires flutter_cache_manager ^0.1.1.
Thus, flutter_test from sdk is incompatible with cached_network_image ^0.4.1.
So, because daily_purify depends on both cached_network_image ^0.4.1+1 and flutter_test any from sdk, version solving failed.

pub get failed (1)

**Comment by zhujian1989** [comment]
因为那些库可能跟不上最新的flutter sdk了，你可以去pub查看最新的版本更新
