### ISSUE TITLE
在moduleflutter下没有.android这个目录

### ISSUE THREAD

**Issue by macroswang** [zhujian1989/MyArchitecture#2]
在moduleflutter下没有.android这个目录，不知道重新创建的项目下的.android目录可不可以代替？

**Comment by jp1017** [comment]
先在setting.gradle下注释掉flutter相关，sync一下，成功后，在打开这个flutter相关, 就有.android了，再sync

**Comment by StudentSort** [comment]
先用AndroidStudio打开一次moduleflutter这个项目，会自动生成.android .ios等文件夹。然后再打开这个项目就好了
